---
# tasks file for deregister-asgs-of-elb
- name: Get information of all ASGs
  ec2_asg_facts:
    region: "{{ elb.region }}"
  register: asg_facts

- name: Get the names of the ASG that point to the desired ELB
  set_fact: asg_name="{{ item.auto_scaling_group_name }}"
  with_items: "{{ asg_facts.results }}"
  when: elb.name in item.load_balancer_names

- name: Remove the old ASG from the ELB
  command: 'aws autoscaling detach-load-balancers --region {{ elb.region }} --auto-scaling-group-name {{ asg_name }} --load-balancer-names {{ elb.name }}'
  when: asg_name is defined
